### ISSUE TITLE
OFF command issues

### ISSUE THREAD

**Issue by nitaybz** [oronbz/homebridge-omxplayer#1]
Hi!
Wanted to share my latest errors when using your plugin...

When Off command is sent while the player is closed I got this error:
```
Aug 13 11:29:00 raspberrypi homebridge[3070]: [2017-8-13 11:29:00] [Coldplay Babies Go] Setting omxplayer switch to 0
Aug 13 11:29:00 raspberrypi homebridge[3070]: [2017-8-13 11:29:00] [Coldplay Babies Go] Stopping player.
Aug 13 11:29:00 raspberrypi homebridge[3070]: /usr/lib/node_modules/homebridge-omxplayer/node_modules/node-omxplayer/index.js:108
Aug 13 11:29:00 raspberrypi homebridge[3070]: throw new Error('Player is closed.');
Aug 13 11:29:00 raspberrypi homebridge[3070]: ^
Aug 13 11:29:00 raspberrypi homebridge[3070]: Error: Player is closed.
Aug 13 11:29:00 raspberrypi homebridge[3070]: at writeStdin (/usr/lib/node_modules/homebridge-omxplayer/node_modules/node-omxplayer/index.js:108:10)
Aug 13 11:29:00 raspberrypi homebridge[3070]: at EventEmitter.Omx.omxplayer.quit (/usr/lib/node_modules/homebridge-omxplayer/node_modules/node-omxplayer/index.js:148:27)
Aug 13 11:29:00 raspberrypi homebridge[3070]: at Player.quit (/usr/lib/node_modules/homebridge-omxplayer/lib/player.js:13:14)
Aug 13 11:29:00 raspberrypi homebridge[3070]: at OmxPlayer._setOn (/usr/lib/node_modules/homebridge-omxplayer/index.js:50:21)
Aug 13 11:29:00 raspberrypi homebridge[3070]: at emitMany (events.js:146:13)
Aug 13 11:29:00 raspberrypi homebridge[3070]: at Characteristic.On.emit (events.js:223:7)
Aug 13 11:29:00 raspberrypi homebridge[3070]: at Characteristic.On.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
Aug 13 11:29:00 raspberrypi homebridge[3070]: at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:733:22)
Aug 13 11:29:00 raspberrypi homebridge[3070]: at Array.forEach (native)
Aug 13 11:29:00 raspberrypi homebridge[3070]: at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:678:8)
```

This error occur when homebridge crushed or restarted and the first command was "OFF":
```
Aug 13 00:38:49 raspberrypi homebridge[2943]: [2017-8-13 00:38:49] [Coldplay Babies Go] Setting omxplayer switch to 0
Aug 13 00:38:49 raspberrypi homebridge[2943]: [2017-8-13 00:38:49] [Coldplay Babies Go] Stopping player.
Aug 13 00:38:49 raspberrypi homebridge[2943]: /usr/lib/node_modules/homebridge-omxplayer/index.js:50
Aug 13 00:38:49 raspberrypi homebridge[2943]: this.player.quit();
Aug 13 00:38:49 raspberrypi homebridge[2943]: ^
Aug 13 00:38:49 raspberrypi homebridge[2943]: TypeError: Cannot read property 'quit' of null
Aug 13 00:38:49 raspberrypi homebridge[2943]: at OmxPlayer._setOn (/usr/lib/node_modules/homebridge-omxplayer/index.js:50:20)
Aug 13 00:38:49 raspberrypi homebridge[2943]: at emitMany (events.js:146:13)
Aug 13 00:38:49 raspberrypi homebridge[2943]: at Characteristic.On.emit (events.js:223:7)
Aug 13 00:38:49 raspberrypi homebridge[2943]: at Characteristic.On.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
Aug 13 00:38:49 raspberrypi homebridge[2943]: at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:733:22)
Aug 13 00:38:49 raspberrypi homebridge[2943]: at Array.forEach (native)
Aug 13 00:38:49 raspberrypi homebridge[2943]: at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:678:8)
Aug 13 00:38:49 raspberrypi homebridge[2943]: at emitMany (events.js:146:13)
Aug 13 00:38:49 raspberrypi homebridge[2943]: at HAPServer.emit (events.js:223:7)
Aug 13 00:38:49 raspberrypi homebridge[2943]: at HAPServer._handleCharacteristics (/usr/lib/node_modules
```
When using the accessory is inside automations or scenes it is very common that OFF/ON commands will be sent while the accessory is already in that state... which leads m to my next issue:

When sending ON command while the accessory is already playing there will be another (same) song playing in parallel... which is not very useful.

When that error occur it is impossible to close the playing song from homekit and it is require to "kill" the program from the terminal.

So I suggest making sure only one session from each accessory can be played at once, and OFF command when nothing is playing will simply do nothing.

Thanks a lot for the plugin! I love it!

**Comment by oronbz** [comment]
#2
